name: push-ec2-app-server
on:
  push:
    branches:
      - master

jobs:
  AUTO_DEPLOY:
    runs-on: ubuntu-latest
    name: Build
    steps:
#      - name: Run scripts in server1
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.KEY }}
#          port: ${{ secrets.PORT }}
#          script: |
#            cd Daengbuhae-Backend
#            git pull ssh master
#            pm2 reload Klapoo_backend
      - name: Run scripts in server2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST2 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd Daengbuhae-Backend
            git pull ssh master
            pm2 reload Klapoo_backend 
        
